In [2]:
#we will be looking at self-attention
#consider the following example 

import torch
torch.manual_seed(1337)
B,T,C = 4,8,2 #batch,time,channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [7]:
#we want x[b, t] = mean_{i<=t} x[b,i] -> The word will be calculating using average of predecessors
xbow = torch.zeros((B,T,C)) #bow is 'bag of words'
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1] #(t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [8]:
#we can achieve the same result as above using Matrix multiplication, which is computationally less expensive
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3)) #produces a lower right triangle of ones
a = a / torch.sum(a, 1, keepdim=True) #make each row sum to one
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b
print(a)
print(b)
print(c)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
